language: python
python:
    - "nightly"
    - 3.6
    - 3.5
    - 3.4
    - 2.7
sudo: false
install:
    - pip install --upgrade pip && pip install .
    - pip install traitlets[test] pytest-cov codecov pytest-warnings --upgrade
script:
    - py.test --cov traitlets -v traitlets
after_success:
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
